---
title: "Title"
author: "Christian Oppegård Moen"
date: "DD MM YYYY"
output: 
  bookdown::pdf_document2:
    toc_depth: '3' # Depth of contents
    number_sections: false
  # pdf_document:
  # #   toc: no
  #   toc_depth: '3'
subtitle: Course
urlcolor: blue
editor_options: 
  chunk_output_type: console
header-includes:
- \usepackage[width=0.8\textwidth]{caption} # add caption to figures.
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  echo = T, tidy=T, message=F, warning=F,
  strip.white=F, # Strips whitespace
  prompt=F, #?
  cache=T, # Cache for quick knit.
  # root.dir = "./subfolder",
  size="scriptsize",
  fig.width=7, 
  fig.height=5, 
  fig.align = "center"
)
```



```{r config, include=F}
if (F){
  setwd("C:/Users/kikka/OneDrive - NTNU/Fysmat/8 Semester V2022/RomStat/romstat/project3")
  options(error=recover)
  options(error=NULL)
}
```

# Data
Dataformat is of tab separated values regarding noise on campus. Some variables are shown in the printout below. The response is `spm3` and `spm4` which are "trivsel" and "effektivitet", respectively. The response is evaluated for each building block.
## Load data
```{r load, options}
# d = read.delim("C:/Users/kikka/OneDrive - NTNU/Fysmat/10 Semester V2023/EiT/TTT4850/data/data-315297-2023-02-09-1558-utf.txt", header=T)
# d = read.delim("./data/data-315297-2023-02-15-1118-utf.txt", header=T)
# head(d[1:5])
```

## Reformat dumb shit
```{r reformatTime, options}
d = read.delim("./data/data-315297-2023-02-22-0953-utf.txt", header=T)

# Time
formatTime <- function(t) {
  tSplit = strsplit(t, ' ')[[1]]
  s=0
  for (i in seq(1, length(tSplit), 2)){
    s = s + switch(
      tSplit[i+1],
      "dager" = strtoi(tSplit[i])*24*3600,
      "dag" = strtoi(tSplit[i])*24*3600,
      "timer" = strtoi(tSplit[i])*3600,
      "time" = strtoi(tSplit[i])*3600,
      "minutt" = strtoi(tSplit[i])*60,
      "minutter" = strtoi(tSplit[i])*60,
      "sekunder" = strtoi(tSplit[i]),
      "sekund" = strtoi(tSplit[i]),
      0
    )
  }
  return(s)
}

ftimes = unlist(lapply(d$Svartid, formatTime))
cbind(d$Svartid, ftimes)
# d$Svartid=ftimes

# Free text answers

```

```{r freeTextToFile, options}
write.csv(d[d[,'spmTekst']!="",c('NR','spmTekst')],"./data/freeTxt.csv", row.names = FALSE)

```

## Make response
As mentioned, the responses are `spm3` and `spm4`.
```{r meanPerBuilding, options}
# head(d)
# variates = names(d)
# yt = d$spmTriv
# ye = d$spmEff
locs = unique(d$spmHvor)
locs
```


```{r anc, options}
N = length(d[,1])
ancPercentage = length(d$spmTiltak_1[d$spmTiltak_1=='mNc']) / N
ancPercentage
```

```{r response, options}
yBuilding = data.frame(
  matrix(ncol=length(locs),
         nrow=2, 
         dimnames=list(c('trivsel', 'effektivitet'), locs))
  )
for (loc in locs){
  # browser()
  yBuilding[loc] = c(mean(d$spmTriv[d$spmHvor==loc]),
             mean(d$spmEff[d$spmHvor==loc]))
} 
yBuilding[1:5]
```
`` 

```{r barplotSave, include=FALSE, eval=FALSE}
# æ is \u00E6
# ø is \u00F8
# å is \u00E5
pdf(file = './figures/histTrivsel&Effektivitet.pdf', width = 10,height = 6)
barplot(
  ((as.matrix(yBuilding))), 
  col = c("lightblue", 'darkblue'),
  border = "white",
  # main="Trivsel",
  ylab="P\u00E5virkning",
  beside = T,
  las=2,
  ylim = c(0,5)
  # space=0.1
)
legend(
  "top",
  legend = c("Trivsel", "Effektivitet"),
  fill = c("lightblue", 'darkblue'), bty = 'n')
dev.off()
```
```{r barplotResponses, options}
# æ is \u00E6
# ø is \u00F8
# å is \u00E5
barplot(
  ((as.matrix(yBuilding))), 
  col = c("lightblue", 'darkblue'),
  border = "white",
  # main="Trivsel",
  ylab="P\u00E5virkning",
  beside = T,
  las=2,
  ylim = c(0,5)
  # space=0.1
)
legend(
  "top",
  legend = c("Trivsel", "Effektivitet"),
  fill = c("lightblue", 'darkblue'), bty = 'n')
```

